### ISSUE TITLE
Vertical traffic-light alignment/bleed issue on 1.18/"one light"

### ISSUE THREAD

**Issue by jbergstroem** [lexicalunit/no-title-bar#17]
<img width="701" alt="screen shot 2017-05-17 at 10 22 24 am" src="https://cloud.githubusercontent.com/assets/176984/26158781/c2ed55b4-3aea-11e7-9714-91ca8e5608c4.png">

this is:
- atom 1.18.0-beta0
- style modifiations as shown on screen
- "one light" theme
- firewatch syntax theme
- "custom" titlebar style

two issues:
 - looks like traffic lights aren't vertically aligned
 - there seems to be a 1px:ish (who knows these days with retina :) bleed of the background from the active tab

I'm not super familiar with atom theming, so apologies for not filing a pull request; but if I get some time later today I will look into it. I can confirm that the "bleed" doesn't occur on a "hidden titlebar" setting.

**Comment by jbergstroem** [comment]
Bleed update: So, the negative margin-top seems correctly calculated to -22px, but in my case the bleed goes away with -23px meaning I'm getting a border or something somewhere.

**Comment by lexicalunit** [comment]
It seems that the `atom-panel-container.left:empty` selector is no longer working like I want it to. What used to happen when the tree-view is hidden is that it became "empty" and that triggered some offsetting in the stylesheet to adjust the position of the traffic lights. I'll have to try and figure out a better way to do this now with Atom docks. Hrmmmmm...

**Comment by lexicalunit** [comment]
Oh wait. You're talking about that thin horizontal light colored line at the top of the window! That is also kinda weird. Hrmmmmmm!

**Comment by lexicalunit** [comment]
@jbergstroem I can no longer recreate this issue on Atom 1.19.0 beta with no-title-bar version 1.1.1.

**Comment by jbergstroem** [comment]
Sorry to say, but the vertical alignment is still an issue for me.

**Comment by lexicalunit** [comment]
Are you seeing something similar to this, @jbergstroem?

With tree-view hidden:
<img width="759" alt="screen shot 2017-06-23 at 4 29 29 pm" src="https://user-images.githubusercontent.com/1903876/27501156-33fc20c4-5831-11e7-9021-bb543bae81a7.png">

With tree-view visible:
<img width="810" alt="screen shot 2017-06-23 at 4 29 20 pm" src="https://user-images.githubusercontent.com/1903876/27501155-33f8fa84-5831-11e7-96c6-c7d283945bf0.png">

**Comment by jbergstroem** [comment]
> @lexicalunit  said:
> Are you seeing something similar to this, @jbergstroem?

Spot on (I have tree-view on right):
<img width="530" alt="screen shot 2017-06-23 at 5 39 43 pm" src="https://user-images.githubusercontent.com/176984/27501400-04cac4ea-583b-11e7-9f49-1b14efaf97a0.png">

**Comment by lexicalunit** [comment]
I see how to fix this now! Give me a while to figure out how to get the LESS CSS to work like I want it to...

**Comment by lexicalunit** [comment]
Ok, give v1.1.3 a try :)

**Comment by jbergstroem** [comment]
Sorry to say this, but I'm still having issues. I'm also getting a small border below the traffic-lights (to the reserved width area):
<img width="380" alt="screen shot 2017-06-27 at 11 33 18 am" src="https://user-images.githubusercontent.com/176984/27596072-71a562a2-5b2c-11e7-884b-c923a528b335.png">

Theme: one light
Version: atom 1.19.0-beta1
Style changes (mainly related to tree-view, but posting for completeness):
```css
atom-pane.active .tab.active:before {
  background: inherit;
}

atom-dock.right ul.list-inline.tab-bar.inset-panel {
  display: none;
}

.no-title-bar:not(.fullscreen).custom-title-bar
  > atom-workspace atom-workspace-axis.horizontal {
  margin-top: -23px !important;
}

.theme-one-light-ui {
  .tab-bar {
    font-size: 12px;
    .tab {
      box-shadow: none;
      border: none;
    }
  }
  .tree-view {
    font-size: 11px;
  }
  .status-bar {
    font-size: 11px;
  }
  .atom-dock-inner.left.atom-dock-open {
    border: none;
  }
  .status-bar .icon:before {
    top: 2px;
  }
}
```

**Comment by lexicalunit** [comment]
Ah, I see what is going on here I think. I added some small tweaks to the v1.3.0 release for Atom 1.19.0+ that should address this issue. Ty for the report @jbergstroem!

**Comment by jbergstroem** [comment]
Just wanted to say that vertical-aligning is still off. This is 1.20 beta and it seems like they're now not stuck to top, but to bottom. Likely the result of incorrect calculations?
<img width="312" alt="screen shot 2017-08-08 at 5 17 34 pm" src="https://user-images.githubusercontent.com/176984/29095046-92354c88-7c5d-11e7-8e5f-414a062f1123.png">

Full css on top of one light, tree-view still on right side:
```less
.no-title-bar:not(.fullscreen):not(.hidden-title-bar) {
  .theme-one-light-ui {
    atom-panel-container.left + atom-workspace-axis.vertical {
      .pane:nth-child(1) .tab-bar {
        margin-left: 0 !important;
        .tab:nth-child(1):not(.active) {
          border-left: 0 !important;
        }
      }
    }
  }
}

.theme-one-light-ui {
  .tab-bar .tab {
    box-shadow: none;
    border: none;
  }
  .tree-view {
    font-size: 11px;
  }
  .status-bar {
    font-size: 11px;
  }
  .atom-dock-inner.left.atom-dock-open {
    border: none;
  }
  .status-bar .icon:before {
    top: 2px;
  }

  atom-pane.active .tab.active:before {
    background: inherit;
  }

  atom-dock.right ul.list-inline.tab-bar.inset-panel {
    display: none;
  }
  .list-tree.has-collapsable-children .list-nested-item > .list-item::before {
    top: 2px;
  }

  .list-tree.has-collapsable-children .list-nested-item
    > .list-item.project-root-header::before {
    top: 0;
  }
}
```
