### ISSUE TITLE
Right-side tree-view draws titlebar

### ISSUE THREAD

**Issue by jbergstroem** [lexicalunit/no-title-bar#31]
Hi, it's me again. After the recent updates, my right tree-view now gets a titlebar:
<img width="1262" alt="screen shot 2017-09-02 at 2 47 09 pm" src="https://user-images.githubusercontent.com/176984/29997616-e001ffb2-8fed-11e7-9b2d-663a44563344.png">

Same settings as before; One light UI, custom titlebar. Stylesheet (tried disabling everything):
```less
.no-title-bar:not(.fullscreen):not(.hidden-title-bar) {
  .theme-one-light-ui {
    atom-panel-container.left + atom-workspace-axis.vertical {
      .pane:nth-child(1) .tab-bar {
        margin-left: 0 !important;
        .tab:nth-child(1):not(.active) {
          border-left: 0 !important;
        }
      }
    }
  }
}

.theme-one-light-ui {
  .tab-bar .tab {
    box-shadow: none;
    border: none;
  }
  .tree-view {
    font-size: 11px;
  }
  .status-bar {
    font-size: 11px;
  }
  .atom-dock-inner.left.atom-dock-open {
    border: none;
  }
  .status-bar .icon:before {
    top: 2px;
  }

  atom-pane.active .tab.active:before {
    background: inherit;
  }

  atom-dock.right ul.list-inline.tab-bar.inset-panel {
    display: none;
  }
  .list-tree.has-collapsable-children .list-nested-item > .list-item::before {
    top: 2px;
  }

  .list-tree.has-collapsable-children
    .list-nested-item
    > .list-item.project-root-header::before {
    top: 0;
  }
}

```
